unbind r
bind r source-file ~/.config/tmux/tmux.conf

if-shell '[ "(uname -m)" = "x86_64" ]' \
    'set-option -g default-command "arch -x86_64 /bin/zsh -l"' \


# Increase or decrease to your liking
bind -r Left resize-pane -L 1
bind -r Down resize-pane -D 1
bind -r Up resize-pane -U 1
bind -r Right resize-pane -R 1

set -g default-terminal "tmux-256color"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g prefix C-s

set -g main-pane-width width
set -g main-pane-height height

set -g detach-on-destroy off

set -g status-style 'bg=terminal'

# Append KITTY_LISTEN_ON to the existing update-environment list
set -ga update-environment KITTY_LISTEN_ON

# F1 - F4 bindings for filepro to send proper escape values
bind-key -n F1 send Escape [11~
bind-key -n F2 send Escape [12~
bind-key -n F3 send Escape [13~
bind-key -n F4 send Escape [14~

# These keys seems to work fine natively
# bind-key -n F5 send Escape [15~
# bind-key -n F6 send Escape [17~
# bind-key -n F7 send Escape [18~
# bind-key -n F8 send Escape [19~
# bind-key -n F9 send Escape [20~
# bind-key -n F10 send Escape [21~
# bind-key -n F11 send Escape [23~
# bind-key -n F12 send Escape [24~
# bind-key -n Home send Escape [1~

unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

set-window-option -g mode-keys vi
# set-window-option -g xterm-keys on
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key x kill-pane

bind-key C-^ run-shell 'tmux select-layout "$(cat ~/.config/tmux/layouts/filepro_6)"'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'sainnhe/tmux-fzf'

bind-key "T" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^e tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-e:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

##### Display Popups #####

bind C-f display-popup \
  -w 80% \
  -h 80% \
  -E 'spotatui'

bind C-n display-popup \
  -w 80% \
  -h 80% \
  -E "nvim \"$(/Users/sbrewer/.config/scripts/daily_note.py path)\""

set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor "abyss"  # Optional: defaults to lagoon_dark

set -g status-position top

if-shell 'test ! -d ~/.config/tmux/plugins/tpm || [ -z "$(ls -A ~/.config/tmux/plugins/tpm 2>/dev/null)" ]' \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm'"

run '~/.config/tmux/plugins/tpm/tpm'
