wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 4, 10, 4, 90]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Central: "America/Chicago"
        Eastern: "America/Detroit"
        Mountain D: "America/Denver"
        Mountain S: "America/Phoenix"
        Pacific: "America/Los_Angeles"
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 15
      sort: "alphabetical"
      title: "Clocks"
      type: "clocks"
    hackernews:
      enabled: true
      numberOfStories: 10
      position:
        top: 3
        left: 0
        width: 2
        height: 1
      storyType: top
      refreshInterval: 15m
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    textfile:
      enabled: true
      filePath: "~/.config/wtf/config.yml"
      format: true
      position:
        top: 4
        left: 0
        height: 3
        width: 2
      refreshInterval: 30
      wrapText: false
    uptime:
      args: []
      cmd: "uptime"
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
