[colors]
background = "#131513"
cursor_bg = "#efbf38"
cursor_border = "#efbf38"
cursor_fg = "#282c34"
foreground = "#cccccc"
selection_bg = "#b9c0ca"
selection_fg = "#272b33"

ansi = [
    "#171517",
    "#ffa600",
    "#ff0066",
    "#20df6c",
    "#6600ff",
    "#5fb9bc",
    "#007fff",
    "#f5f5f5"
]
brights = [
    "#383338",
    "#ffa600",
    "#ff0066",
    "#20df6c",
    "#6600ff",
    "#4483aa",
    "#007fff",
    "#f7f3f7"
]
