#!/usr/bin/env bash

# FONT_FACE="Hurmit Nerd Font"

export PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
export ITEM_DIR="$HOME/.config/sketchybar/items"

source "$CONFIG_DIR/colors.sh"

source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/defaults.sh"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/spotify.sh"

sketchybar --update
